#!/bin/sh
# =============================================================================
# Netboot Server - Container Entrypoint
# =============================================================================
# Auto-detects network configuration and generates config files, then starts
# supervisord to manage all services (dnsmasq, smbd, nginx, auth).
# =============================================================================

set -e

# ---------------------------------------------------------------------------
# Auto-detect server IP if not set
# ---------------------------------------------------------------------------
IFACE="${DHCP_INTERFACE:-eth0}"

if [ -z "$TFTP_SERVER_IP" ]; then
    # Auto-detect IP from the network interface
    TFTP_SERVER_IP=$(ip -4 addr show "$IFACE" 2>/dev/null | grep -oP 'inet \K[\d.]+' | head -1)
    if [ -n "$TFTP_SERVER_IP" ]; then
        echo "[entrypoint] Auto-detected server IP: $TFTP_SERVER_IP (from $IFACE)"
    else
        echo "[entrypoint] WARNING: Could not detect IP for interface $IFACE"
        echo "[entrypoint] Set TFTP_SERVER_IP in .env file"
        TFTP_SERVER_IP="192.168.1.100"
    fi
else
    echo "[entrypoint] Using configured server IP: $TFTP_SERVER_IP"
fi

# Derive subnet from server IP (assume /24)
SERVER_SUBNET="$(echo "$TFTP_SERVER_IP" | sed 's/\.[0-9]*$/.0/')"

# ---------------------------------------------------------------------------
# Derive SMB allowed subnet from TFTP_SERVER_IP if not explicitly set
# ---------------------------------------------------------------------------
if [ -z "$SMB_ALLOWED_SUBNET" ]; then
    SMB_ALLOWED_SUBNET="${SERVER_SUBNET}/24"
    echo "[entrypoint] SMB_ALLOWED_SUBNET derived: $SMB_ALLOWED_SUBNET"
else
    echo "[entrypoint] Using configured SMB_ALLOWED_SUBNET: $SMB_ALLOWED_SUBNET"
fi

# ---------------------------------------------------------------------------
# Update dnsmasq.conf with correct server IP and subnet
# ---------------------------------------------------------------------------
DNSMASQ_CONF="/etc/dnsmasq.conf"
HTTP_PORT="${HTTP_PORT:-8080}"

if [ -f "$DNSMASQ_CONF" ]; then
    echo "[entrypoint] Updating dnsmasq.conf with server IP: $TFTP_SERVER_IP"

    # Update interface
    sed -i "s/^interface=.*/interface=$IFACE/" "$DNSMASQ_CONF"

    # Update proxy DHCP range with detected subnet
    sed -i "s/^dhcp-range=.*,proxy/dhcp-range=$SERVER_SUBNET,proxy/" "$DNSMASQ_CONF"

    # Update iPXE chain URL with detected/configured IP
    sed -i "s|dhcp-boot=tag:ipxe,http://[^/]*/|dhcp-boot=tag:ipxe,http://$TFTP_SERVER_IP:$HTTP_PORT/|" "$DNSMASQ_CONF"

    echo "[entrypoint] dnsmasq.conf updated successfully"
fi

# ---------------------------------------------------------------------------
# Generate /etc/samba/smb.conf
# ---------------------------------------------------------------------------
echo "[entrypoint] Generating /etc/samba/smb.conf (allowed subnet: $SMB_ALLOWED_SUBNET)"

cat > /etc/samba/smb.conf << EOF
# Auto-generated by entrypoint.sh — do not edit manually
[global]
   server role = standalone server
   log file = /dev/stdout
   log level = 1
   map to guest = Bad User
   hosts allow = ${SMB_ALLOWED_SUBNET} 127.0.0.1
   hosts deny = 0.0.0.0/0
   interfaces = ${IFACE}
   bind interfaces only = yes

[images]
   comment = Netboot Server - OS Images
   path = /srv/images
   browseable = yes
   read only = yes
   guest ok = yes
   force user = nobody
   acl allow execute always = yes
EOF

echo "[entrypoint] smb.conf generated successfully"

# ---------------------------------------------------------------------------
# Generate /etc/exports for NFS (unfs3 userspace NFS server)
# ---------------------------------------------------------------------------
echo "[entrypoint] Generating /etc/exports (allowed subnet: $SMB_ALLOWED_SUBNET)"

# Convert CIDR notation to NFS-compatible format
# unfs3 expects subnet in format: 192.168.1.0/255.255.255.0
NFS_SUBNET=$(echo "$SMB_ALLOWED_SUBNET" | sed 's|/24|/255.255.255.0|; s|/16|/255.255.0.0|; s|/8|/255.0.0.0|')

cat > /etc/exports << EOF
# Auto-generated by entrypoint.sh — do not edit manually
# Export images directory for Proxmox/TrueNAS PXE boot (unfs3)
# Restricted to allowed subnet: $SMB_ALLOWED_SUBNET
/srv/images ${NFS_SUBNET}(ro,no_root_squash,insecure)
EOF

echo "[entrypoint] /etc/exports generated successfully"

# ---------------------------------------------------------------------------
# Start supervisord (replaces this process)
# ---------------------------------------------------------------------------
echo "[entrypoint] Starting supervisord ..."
exec supervisord -c /etc/supervisord.conf
